#!/usr/bin/env bash

cd "/mnt/c/Users/ryan/Documents/Lent recordings - Carlos/New"

for f in *.m4a
  do
    avconv -i "${f}" -acodec libopus -b:a 16k -ac 1 -application voip -vbr on -compression_level 10 "../${f%.m4a}.opus"
    mv "${f}" ../Full
  done
